# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.
# These values are expected to rarely change. If you are editing this file
# very often, consider using Jekyll's data files feature.

## Site settings
## https://jekyllrb.com/docs/configuration/

# Plugins
plugins:
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Conversion
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Serving
baseurl: ""

# Input files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CNAME

# Output
permalink: title

## Site variables
## accessible via `{{ site.* }}` in layouts.
